baseURL = "https://openjam.io"
languageCode = "en-us"
title = "Open Jam"

theme = "terminal"

# canonifyURLs = true
# relativeURLs = true

copyright = "hi"

[social]
    discord = "https://discord.gg/8uDjRgj"
    itch = "https://itch.io/jam/open-jam-2020"
    twitter = "https://twitter.com/openjamio"
    irc = "https://webchat.freenode.net/#openjam"

# terminal theme params
[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon.ico"


[languages]
  [languages.en]
    languageName = "English"
    subtitle = "a game jam dedicated to open source."
    keywords = "gamdev, gaming, game jam, gamejam"
    copyright = "@ Open Jam"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Open Jam"
      logoImage = "/logo/open-jam-logo.png"
      logoHomeLink = "/"
      logoTagline = 'Open Jam is an annual, weekend-long open-source game jam. Sign up, and create open source games using freely available development tools.<br><br><strong>Open Jam 2021 begins on <pfe-datetime datetime="october 1 2021 1:00 pm edt" type="local" day="numeric" month="long" year="numeric" locale>October 1, 2021</pfe-datetime>.</strong>'


    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "2021"
        name = "2021 Sign-ups"
        url = "https://itch.io/jam/open-jam-2021"
      [[languages.en.menu.main]]
        identifier = "past-jams"
        name = "Past Jams"
        url = "/tags/recap"
      [[languages.en.menu.main]]
        identifier = "brand"
        name = "Brand"
        url = "/brand"


[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
